### ISSUE TITLE
Transfer project to sugarlabs

### ISSUE THREAD

**Issue by davelab6** [godiard/domino-activity#2]
🎯

**Comment by leonardcj** [comment]
Please consider transferring

**Comment by quozl** [comment]
It's really up to the developer.  I've forked several activity repositories to the _sugarlabs_ organisation on GitHub instead, and can do that for _domino_ as well.  I don't have commit rights to _domino_.

**Comment by godiard** [comment]
I maintained many orphan activities, in that cases, I prefer transfer the activity to Sugarlabs. In the case of Domino, I created the activity then I prefer keep in my user and give commit rights. quozl and leonardcj added as colaborators
